name: smorfenv
channels:
  - conda-forge
  - bioconda
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - pyyaml>=6.0.1
  - biopython>=1.81
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tqdm>=4.65.0
  - pytest>=7.0.0
  - psutil>=5.9.0
  - sentencepiece
  - pytorch>=2.0.0
  - pytorch-cuda=12.1
  - cudatoolkit=11.8
  - pip=23.3.1
  - pip:
      - biopython
      - datasets
      - einops
      - enformer-pytorch
      - fsspec
      - genomic-benchmarks
      - git-lfs
      - h5py
      - huggingface-hub
      - hydra-core
      - ipdb
      - matplotlib
      - notebook
      - nvitop
      - omegaconf
      - pandas
      - pyfaidx
      - pysam
      - pytest
      - pytorch-lightning
      - rich
      - seaborn
      - scikit-learn
      - timm
      - torch
      - torchaudio
      - torchdata
      - torchmetrics
      - torchtext
      - torchvision
      - tqdm
      - transformers
      - triton
      - wandb
      - mamba-ssm
