preprocessing:
  chunk_size: 5000
  input:
    fasta_dir: "data/10_fasta"
    gff_dir: "data/10_gff"
  output:
    dir: "data/processed"
  logging:
    level: "INFO"
    file: "logs/preprocessing.log"
